name: scheduled_timer
description: A simple timer that can be scheduled to run at a specific time, and will restore it's scheduled time across app restarts.
version: 1.0.0
homepage: https://github.com/magnuswikhog/scheduled_timer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: '>=0.5.12+4 <2.0.0'



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
